Repository surfstudio/flutter-otp-autofill, pull requests merged in 2023-02, with the labels that each got.

#35 Fixed Android example didn't attach the activity
  CHANGELOG.md
  example/android/app/build.gradle
  example/android/app/src/main/kotlin/com/example/test_otp_autofill/MainActivity.kt
  pubspec.yaml
Labels: bug, new pull request

#42 Added PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: new pull request

#36 Phone number hint API update
  CHANGELOG.md
  android/build.gradle
  android/src/main/kotlin/ru/surfstudio/otp_autofill/OTPPlugin.kt
  pubspec.yaml
Labels: bug, enhancement, new pull request
