Repository surfstudio/flutter-otp-autofill, pull requests merged in 2023-07, with the labels that each got.

#52 fix(SNP-400): Updates build badge route.
  README.md
Labels: bug, new pull request

#58 feat(workflow): Update workflow usage
  .fvm/fvm_config.json
  .github/workflows/main.yml
  .github/workflows/publish_to_pub.yml
  .gitignore
  README.md
  example/lib/main.dart
  example/pubspec.yaml
  pubspec.yaml
Labels: enhancement, new pull request

#57 fix: possible crash
  android/src/main/kotlin/ru/surfstudio/otp_autofill/OTPPlugin.kt
Labels: enhancement, WIP

#49 fix: Fix listener stopping on dispose
  android/src/main/kotlin/ru/surfstudio/otp_autofill/OTPPlugin.kt
  example/.fvm/fvm_config.json
  example/.gitignore
  example/android/app/src/main/kotlin/ru/surfstudio/otp_autofill_example/MainActivity.kt
  example/lib/main.dart
Labels: bug, new pull request

#59 feat: Kotlin and Gradle update
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  example/.fvm/flutter_sdk
  example/android/build.gradle
  pubspec.yaml
Labels: enhancement, new pull request

#61 feat(workflow): added dev branch to main workflow
  .github/workflows/main.yml
Labels: enhancement, new pull request

#62 docs: Add changelog for v.3.0.0
  CHANGELOG.md
Labels: documentation, new pull request

#63 Release v.3.0.0
  .github/workflows/main.yml
  CHANGELOG.md
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/src/main/kotlin/ru/surfstudio/otp_autofill/OTPPlugin.kt
  docs/TESTING.md
  docs/assets/testing/signature-code.png
  docs/assets/testing/sms-code-paste.png
  docs/assets/testing/sms-received.png
  example/.fvm/flutter_sdk
  example/.fvm/fvm_config.json
  example/.gitignore
  example/android/app/src/main/kotlin/ru/surfstudio/otp_autofill_example/MainActivity.kt
  example/android/build.gradle
  example/lib/main.dart
  pubspec.yaml
Labels: documentation, new pull request

#64 fix(wf): Fix publish workflow
  .github/workflows/publish_to_pub.yml
Labels: enhancement, new pull request

#65 fix: Fix publish workflow
  .github/workflows/publish_to_pub.yml
  pubspec.yaml
Labels: enhancement, new pull request

#66 fix(docs): Fix docs structure
  doc/assets/testing/signature-code.png
  doc/assets/testing/sms-code-paste.png
  doc/assets/testing/sms-received.png
  doc/testing.md
Labels: documentation, new pull request
